[core]
	autocrlf = false

[init]
	defaultBranch = main

[commit]
    gpgsign = true

[push]
	autoSetupRemote = true

[fetch]
    prune = true

[gpg]
	format = ssh

[user]
	signingkey = ~/.ssh/github_ed25519.pub
